# This is a docker-compose file for a postgres database for development purposes

version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: reading-tracker-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reading
      POSTGRES_PASSWORD: reading
      POSTGRES_DB: reading
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
